#!/usr/bin/env bun

/**
 * Setup script for Cast.
 *
 * - Generate .env (preserves existing service vars)
 * - Provision Cloudflare resources (D1, KV, R2, Queue) via wrangler
 * - Generate and store BETTER_AUTH_SECRET as a Cloudflare secret
 * - Install dependencies via bun
 * - Optionally deploy to Cloudflare (remote migrations + wrangler deploy)
 *
 * Usage: bun setup
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";

import { provisionCloudflare } from "./cloudflare.ts";
import { askYesNo, bold, ENV_PATH, green, parseEnvFile, run } from "./helpers.ts";

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

function generateEnv() {
  console.log(bold("\n── .env ──\n"));

  const existing = existsSync(ENV_PATH) ? parseEnvFile(readFileSync(ENV_PATH, "utf8")) : new Map<string, string>();

  const lines: string[] = ["# Auto-generated by setup.ts", ""];

  const optionalVars = [
    "VITE_PUBLIC_POSTHOG_KEY",
    "VITE_PUBLIC_POSTHOG_HOST",
    "RESEND_API_KEY",
    "EMAIL_FROM",
    "VITE_PUBLIC_GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
  ];

  const preserved: string[] = [];
  for (const key of optionalVars) {
    const val = existing.get(key);
    if (val !== undefined) {
      preserved.push(`${key}=${val}`);
    }
  }

  if (preserved.length > 0) {
    lines.push("# Services (preserved from existing .env)");
    lines.push(...preserved);
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
  console.log(green("✓ .env created"));
}

function installDeps() {
  console.log(bold("\n── Dependencies ──\n"));
  run("bun install");
}

async function offerDeploy() {
  // Only offer if authenticated with Cloudflare
  if (!run("npx wrangler whoami", { silent: true })) {
    return;
  }

  const shouldDeploy = await askYesNo("Deploy to Cloudflare now?");
  if (!shouldDeploy) {
    return;
  }

  console.log(bold("\n── Deploy ──\n"));

  console.log("Applying remote migrations...");
  run("bun db:migrate:remote");

  console.log("Deploying...");
  run("bun deploy");

  console.log(green("✓ Deployed"));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  generateEnv();
  provisionCloudflare();
  installDeps();
  await offerDeploy();

  console.log(bold("\n── Done ──\n"));
  console.log(`  ${bold("bun dev")}     Start dev server`);
  console.log(`  ${bold("bun ok")}      Type check + lint + tests`);
  console.log("");
}

void main();
