#!/usr/bin/env bun

/**
 * Setup script for Cast.
 *
 * - Generate .env (preserves existing service vars)
 * - Provision Cloudflare resources (D1, KV, R2, Queue) via wrangler
 * - Generate and store BETTER_AUTH_SECRET as a Cloudflare secret
 * - Install dependencies via bun
 * - Optionally deploy to Cloudflare (remote migrations + wrangler deploy)
 *
 * Usage: bun setup
 */

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

const askYesNo = async (question: string, defaultYes = true): Promise<boolean> => {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const hint = defaultYes ? "[Y/n]" : "[y/N]";
  return new Promise((resolve) => {
    rl.question(`${question} ${hint} `, (answer) => {
      rl.close();
      const trimmed = answer.trim().toLowerCase();
      resolve(trimmed === "" ? defaultYes : trimmed === "y" || trimmed === "yes");
    });
  });
};

// ---------------------------------------------------------------------------
// Constants & formatting
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dirname, "..");
const ENV_PATH = resolve(ROOT, ".env");
const WRANGLER_CONFIG = resolve(ROOT, "wrangler.jsonc");

const bold = (s: string) => `\u001B[1m${s}\u001B[0m`;
const dim = (s: string) => `\u001B[2m${s}\u001B[0m`;
const green = (s: string) => `\u001B[32m${s}\u001B[0m`;
const yellow = (s: string) => `\u001B[33m${s}\u001B[0m`;

// ---------------------------------------------------------------------------
// Shell helpers
// ---------------------------------------------------------------------------

const run = (cmd: string, opts?: { cwd?: string; silent?: boolean }) => {
  try {
    return execSync(cmd, {
      cwd: opts?.cwd ?? ROOT,
      stdio: opts?.silent ? "pipe" : "inherit",
      encoding: "utf8",
    });
  } catch {
    return null;
  }
};

const runJson = <T>(cmd: string): T | null => {
  const out = run(cmd, { silent: true });
  if (!out) {
    return null;
  }
  try {
    return JSON.parse(out) as T;
  } catch {
    return null;
  }
};

// ---------------------------------------------------------------------------
// File helpers
// ---------------------------------------------------------------------------

const parseEnvFile = (content: string): Map<string, string> => {
  const vars = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) {
      continue;
    }
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) {
      continue;
    }
    vars.set(trimmed.slice(0, eqIndex), trimmed.slice(eqIndex + 1));
  }
  return vars;
};

const readWranglerConfig = () => {
  const raw = readFileSync(WRANGLER_CONFIG, "utf8");
  const stripped = raw.replaceAll(/\/\/.*$/gm, "").replaceAll(/\/\*[\s\S]*?\*\//g, "");
  return JSON.parse(stripped);
};

const updateWranglerField = (field: string, value: string) => {
  let content = readFileSync(WRANGLER_CONFIG, "utf8");
  const pattern = new RegExp(`("${field}":\\s*)"[^"]*"`, "g");
  content = content.replace(pattern, `$1"${value}"`);
  writeFileSync(WRANGLER_CONFIG, content);
};

const isPlaceholder = (v: string) => !v || v === "NOT_SET";

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

function generateEnv() {
  console.log(bold("\n── .env ──\n"));

  const existing = existsSync(ENV_PATH) ? parseEnvFile(readFileSync(ENV_PATH, "utf8")) : new Map<string, string>();

  const lines: string[] = ["# Auto-generated by _etc/setup.ts", ""];

  const optionalVars = [
    "VITE_PUBLIC_POSTHOG_KEY",
    "VITE_PUBLIC_POSTHOG_HOST",
    "RESEND_API_KEY",
    "EMAIL_FROM",
    "VITE_PUBLIC_GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
  ];

  const preserved: string[] = [];
  for (const key of optionalVars) {
    const val = existing.get(key);
    if (val !== undefined) {
      preserved.push(`${key}=${val}`);
    }
  }

  if (preserved.length > 0) {
    lines.push("# Services (preserved from existing .env)");
    lines.push(...preserved);
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
  console.log(green("✓ .env created"));
}

function provisionCloudflare() {
  console.log(bold("\n── Cloudflare ──\n"));

  if (!run("npx wrangler whoami", { silent: true })) {
    console.log(yellow("⚠ Not authenticated — skipping resource provisioning"));
    console.log(dim("  Run: npx wrangler login"));
    return;
  }

  const config = readWranglerConfig();
  let changed = false;

  changed = provisionD1(config) || changed;
  changed = provisionKV(config) || changed;
  provisionR2(config);
  provisionQueue(config);

  if (changed) {
    console.log(dim(`\n  Updated ${WRANGLER_CONFIG}`));
  }

  provisionAuthSecret();

  console.log(dim("\n  For CI deploy, add this GitHub Actions secret:"));
  console.log(dim("    CLOUDFLARE_API_TOKEN — dash.cloudflare.com → API Tokens"));
}

function provisionD1(config: Record<string, unknown>): boolean {
  const d1Config = (config.d1_databases as Record<string, string>[] | undefined)?.[0];
  if (!d1Config) {
    return false;
  }

  if (!isPlaceholder(d1Config.database_id)) {
    console.log(dim(`  D1 "${d1Config.database_name}" — already configured`));
    return false;
  }

  const dbName = d1Config.database_name;
  type D1Entry = { uuid: string; name: string };
  const list = runJson<D1Entry[]>("npx wrangler d1 list --json");
  const found = list?.find((db) => db.name === dbName);

  if (found) {
    updateWranglerField("database_id", found.uuid);
    console.log(green(`✓ D1 "${dbName}"`) + dim(` — found (${found.uuid.slice(0, 8)}...)`));
  } else {
    const output = run(`npx wrangler d1 create ${dbName}`, { silent: true });
    const match = output?.match(/database_id\s*=\s*"([^"]+)"/);
    if (match?.[1]) {
      updateWranglerField("database_id", match[1]);
      console.log(green(`✓ D1 "${dbName}"`) + dim(` — created (${match[1].slice(0, 8)}...)`));
    } else {
      console.log(yellow(`⚠ Failed to create D1 "${dbName}"`));
    }
  }
  return true;
}

function provisionKV(config: Record<string, unknown>): boolean {
  const kvConfig = (config.kv_namespaces as Record<string, string>[] | undefined)?.[0];
  if (!kvConfig) {
    return false;
  }

  if (!isPlaceholder(kvConfig.id)) {
    console.log(dim(`  KV "${kvConfig.binding}" — already configured`));
    return false;
  }

  const title = `${(config as Record<string, string>).name}-${kvConfig.binding}`;
  type KvEntry = { id: string; title: string };
  const list = runJson<KvEntry[]>("npx wrangler kv namespace list --json");
  const found = list?.find((ns) => ns.title === title);

  if (found) {
    updateWranglerField("id", found.id);
    console.log(green(`✓ KV "${title}"`) + dim(` — found (${found.id.slice(0, 8)}...)`));
  } else {
    const output = run(`npx wrangler kv namespace create ${kvConfig.binding}`, { silent: true });
    const match = output?.match(/id\s*=\s*"([^"]+)"/);
    if (match?.[1]) {
      updateWranglerField("id", match[1]);
      console.log(green(`✓ KV "${title}"`) + dim(` — created (${match[1].slice(0, 8)}...)`));
    } else {
      console.log(yellow("⚠ Failed to create KV namespace"));
    }
  }
  return true;
}

function provisionR2(config: Record<string, unknown>) {
  const r2Config = (config.r2_buckets as Record<string, string>[] | undefined)?.[0];
  if (!r2Config) {
    return;
  }

  const bucketName = r2Config.bucket_name;
  type R2Entry = { name: string };
  const list = runJson<R2Entry[]>("npx wrangler r2 bucket list --json");

  if (list?.find((b) => b.name === bucketName)) {
    console.log(dim(`  R2 "${bucketName}" — already exists`));
  } else {
    const result = run(`npx wrangler r2 bucket create ${bucketName}`, { silent: true });
    if (result) {
      console.log(green(`✓ R2 "${bucketName}"`) + dim(" — created"));
    } else {
      console.log(yellow(`⚠ Failed to create R2 "${bucketName}"`));
    }
  }
}

function provisionQueue(config: Record<string, unknown>) {
  const queues = config.queues as Record<string, Record<string, string>[]> | undefined;
  const queueConfig = queues?.producers?.[0];
  if (!queueConfig) {
    return;
  }

  const queueName = queueConfig.queue;
  type QueueEntry = { queue_name: string };
  const list = runJson<QueueEntry[]>("npx wrangler queues list --json");

  if (list?.find((q) => q.queue_name === queueName)) {
    console.log(dim(`  Queue "${queueName}" — already exists`));
  } else {
    const result = run(`npx wrangler queues create ${queueName}`, { silent: true });
    if (result) {
      console.log(green(`✓ Queue "${queueName}"`) + dim(" — created"));
    } else {
      console.log(yellow(`⚠ Failed to create queue "${queueName}"`));
    }
  }
}

function provisionAuthSecret() {
  const secretCheck = run("npx wrangler secret list --json", { silent: true });
  if (secretCheck?.includes("BETTER_AUTH_SECRET")) {
    console.log(dim("  BETTER_AUTH_SECRET — already set"));
    return;
  }

  const secret = crypto.randomUUID() + crypto.randomUUID();
  const result = run(`echo "${secret}" | npx wrangler secret put BETTER_AUTH_SECRET`, { silent: true });
  if (result) {
    console.log(green("✓ BETTER_AUTH_SECRET") + dim(" — generated and stored"));
  } else {
    console.log(
      yellow("⚠ Failed to set BETTER_AUTH_SECRET — set it manually: npx wrangler secret put BETTER_AUTH_SECRET")
    );
  }
}

function installDeps() {
  console.log(bold("\n── Dependencies ──\n"));
  run("bun install");
}

async function offerDeploy() {
  // Only offer if authenticated with Cloudflare
  if (!run("npx wrangler whoami", { silent: true })) {
    return;
  }

  const shouldDeploy = await askYesNo("Deploy to Cloudflare now?");
  if (!shouldDeploy) {
    return;
  }

  console.log(bold("\n── Deploy ──\n"));

  console.log("Applying remote migrations...");
  run("bun db:migrate:remote");

  console.log("Deploying...");
  run("bun deploy");

  console.log(green("✓ Deployed"));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  generateEnv();
  provisionCloudflare();
  installDeps();
  await offerDeploy();

  console.log(bold("\n── Done ──\n"));
  console.log(`  ${bold("bun dev")}     Start dev server`);
  console.log(`  ${bold("bun ok")}      Type check + lint + tests`);
  console.log("");
}

void main();
