/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiIconRouteImport } from './routes/api/icon'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiPhSplatRouteImport } from './routes/api/ph.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIconRoute = ApiIconRouteImport.update({
  id: '/api/icon',
  path: '/api/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhSplatRoute = ApiPhSplatRouteImport.update({
  id: '/api/ph/$',
  path: '/api/ph/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/api/icon': typeof ApiIconRoute
  '/api/og': typeof ApiOgRoute
  '/auth/$path': typeof AuthPathRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/api/icon': typeof ApiIconRoute
  '/api/og': typeof ApiOgRoute
  '/auth/$path': typeof AuthPathRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/api/icon': typeof ApiIconRoute
  '/api/og': typeof ApiOgRoute
  '/auth/$path': typeof AuthPathRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ph/$': typeof ApiPhSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/api/icon'
    | '/api/og'
    | '/auth/$path'
    | '/admin/'
    | '/api/auth/$'
    | '/api/ph/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/api/icon'
    | '/api/og'
    | '/auth/$path'
    | '/admin'
    | '/api/auth/$'
    | '/api/ph/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/admin/analytics'
    | '/api/icon'
    | '/api/og'
    | '/auth/$path'
    | '/admin/'
    | '/api/auth/$'
    | '/api/ph/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiIconRoute: typeof ApiIconRoute
  ApiOgRoute: typeof ApiOgRoute
  AuthPathRoute: typeof AuthPathRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPhSplatRoute: typeof ApiPhSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/icon': {
      id: '/api/icon'
      path: '/api/icon'
      fullPath: '/api/icon'
      preLoaderRoute: typeof ApiIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ph/$': {
      id: '/api/ph/$'
      path: '/api/ph/$'
      fullPath: '/api/ph/$'
      preLoaderRoute: typeof ApiPhSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiIconRoute: ApiIconRoute,
  ApiOgRoute: ApiOgRoute,
  AuthPathRoute: AuthPathRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPhSplatRoute: ApiPhSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
