#!/usr/bin/env bun

/**
 * Interactive setup script for Cast.
 *
 * Usage:
 *   bun meta/cast/setup.ts          # Full interactive setup
 *   bun meta/cast/setup.ts --env    # Only generate .env
 *   bun meta/cast/setup.ts --gh     # Only set GitHub secrets
 */

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dirname, "../..");
const ENV_PATH = resolve(ROOT, ".env");

const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;
const green = (s: string) => `\x1b[32m${s}\x1b[0m`;
const yellow = (s: string) => `\x1b[33m${s}\x1b[0m`;

const run = (cmd: string, opts?: { cwd?: string; silent?: boolean }) => {
  try {
    return execSync(cmd, {
      cwd: opts?.cwd ?? ROOT,
      stdio: opts?.silent ? "pipe" : "inherit",
      encoding: "utf8",
    });
  } catch {
    return null;
  }
};

const hasCommand = (cmd: string) => {
  try {
    execSync(`which ${cmd}`, { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
};

/** Parse a .env file into key-value pairs (ignores comments and empty lines). */
const parseEnvFile = (content: string): Map<string, string> => {
  const vars = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    vars.set(trimmed.slice(0, eqIndex), trimmed.slice(eqIndex + 1));
  }
  return vars;
};

// ---------------------------------------------------------------------------
// Steps
// ---------------------------------------------------------------------------

const args = new Set(process.argv.slice(2));
const envOnly = args.has("--env");
const ghOnly = args.has("--gh");
const runAll = !envOnly && !ghOnly;

// ── Step 1: Generate .env ─────────────────────────────────────────────────

if (runAll || envOnly) {
  console.log(bold("\n── .env setup ──\n"));

  const existing = existsSync(ENV_PATH) ? parseEnvFile(readFileSync(ENV_PATH, "utf8")) : new Map<string, string>();

  const lines: string[] = ["# Auto-generated by meta/cast/setup.ts", ""];

  // Preserve existing optional vars
  const optionalVars = [
    "VITE_PUBLIC_POSTHOG_KEY",
    "VITE_PUBLIC_POSTHOG_HOST",
    "RESEND_API_KEY",
    "EMAIL_FROM",
    "VITE_PUBLIC_GOOGLE_OAUTH",
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "VITE_PUBLIC_MAGIC_LINK",
  ];

  const preservedLines: string[] = [];
  for (const key of optionalVars) {
    const val = existing.get(key);
    if (val !== undefined) {
      preservedLines.push(`${key}=${val}`);
    }
  }

  if (preservedLines.length > 0) {
    lines.push("# Services (preserved from existing .env)");
    lines.push(...preservedLines);
    lines.push("");
  }

  writeFileSync(ENV_PATH, lines.join("\n") + "\n");
  console.log(green("✓ .env created"));
  console.log(dim(`  ${ENV_PATH}`));
}

// ── Step 2: GitHub secrets ────────────────────────────────────────────────

if (runAll || ghOnly) {
  console.log(bold("\n── GitHub secrets ──\n"));

  if (!hasCommand("gh")) {
    console.log(yellow("⚠ gh CLI not found — skipping GitHub secrets"));
    console.log(dim("  Install: https://cli.github.com/"));
  } else {
    const authStatus = run("gh auth status", { silent: true });
    if (authStatus === null) {
      console.log(yellow("⚠ gh CLI not authenticated — skipping GitHub secrets"));
      console.log(dim("  Run: gh auth login"));
    } else {
      const existingSecrets = run("gh secret list --json name --jq '.[].name'", { silent: true }) ?? "";
      const secretSet = new Set(existingSecrets.trim().split("\n").filter(Boolean));

      if (secretSet.has("CLOUDFLARE_API_TOKEN")) {
        console.log(dim("  CLOUDFLARE_API_TOKEN — already set"));
      } else {
        console.log(yellow("  Manual setup needed:"));
        console.log(dim("    CLOUDFLARE_API_TOKEN — dash.cloudflare.com → API Tokens"));
        console.log(dim(`\n    gh secret set CLOUDFLARE_API_TOKEN --body "your-token"`));
      }
    }
  }
}

// ── Step 3: Install deps ──────────────────────────────────────────────────

if (runAll) {
  console.log(bold("\n── Dependencies ──\n"));
  run("bun install");
  console.log(green("✓ Dependencies installed"));
}

// ── Done ──────────────────────────────────────────────────────────────────

console.log(bold("\n── Done ──\n"));

if (runAll) {
  console.log(`  ${bold("bun dev")}     Start dev server`);
  console.log(`  ${bold("bun ok")}      Type check + lint + tests`);
  console.log("");
}
