#!/usr/bin/env bun

/**
 * Setup script for Cast — generates .env, provisions Cloudflare resources, installs deps.
 *
 * Usage: bun setup
 */

import { execSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ROOT = resolve(import.meta.dirname, "../..");
const ENV_PATH = resolve(ROOT, ".env");
const WRANGLER_CONFIG = resolve(ROOT, "wrangler.jsonc");

const bold = (s: string) => `\x1b[1m${s}\x1b[0m`;
const dim = (s: string) => `\x1b[2m${s}\x1b[0m`;
const green = (s: string) => `\x1b[32m${s}\x1b[0m`;
const yellow = (s: string) => `\x1b[33m${s}\x1b[0m`;

const run = (cmd: string, opts?: { cwd?: string; silent?: boolean }) => {
  try {
    return execSync(cmd, {
      cwd: opts?.cwd ?? ROOT,
      stdio: opts?.silent ? "pipe" : "inherit",
      encoding: "utf8",
    });
  } catch {
    return null;
  }
};

const runJson = <T>(cmd: string): T | null => {
  const out = run(cmd, { silent: true });
  if (!out) return null;
  try {
    return JSON.parse(out) as T;
  } catch {
    return null;
  }
};

/** Parse a .env file into key-value pairs (ignores comments and empty lines). */
const parseEnvFile = (content: string): Map<string, string> => {
  const vars = new Map<string, string>();
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;
    vars.set(trimmed.slice(0, eqIndex), trimmed.slice(eqIndex + 1));
  }
  return vars;
};

/** Read wrangler.jsonc, strip comments, parse. */
const readWranglerConfig = () => {
  const raw = readFileSync(WRANGLER_CONFIG, "utf8");
  const stripped = raw.replace(/\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");
  return JSON.parse(stripped);
};

/** Write wrangler.jsonc preserving comments by doing targeted replacements. */
const updateWranglerField = (field: string, value: string) => {
  let content = readFileSync(WRANGLER_CONFIG, "utf8");
  const pattern = new RegExp(`("${field}":\\s*)"[^"]*"`, "g");
  content = content.replace(pattern, `$1"${value}"`);
  writeFileSync(WRANGLER_CONFIG, content);
};

const isPlaceholder = (v: string) => !v || v === "NOT_SET";

// ---------------------------------------------------------------------------
// 1. Generate .env
// ---------------------------------------------------------------------------

console.log(bold("\n── .env ──\n"));

const existing = existsSync(ENV_PATH) ? parseEnvFile(readFileSync(ENV_PATH, "utf8")) : new Map<string, string>();

const lines: string[] = ["# Auto-generated by meta/cast/setup.ts", ""];

const optionalVars = [
  "VITE_PUBLIC_POSTHOG_KEY",
  "VITE_PUBLIC_POSTHOG_HOST",
  "RESEND_API_KEY",
  "EMAIL_FROM",
  "VITE_PUBLIC_GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
];

const preservedLines: string[] = [];
for (const key of optionalVars) {
  const val = existing.get(key);
  if (val !== undefined) {
    preservedLines.push(`${key}=${val}`);
  }
}

if (preservedLines.length > 0) {
  lines.push("# Services (preserved from existing .env)");
  lines.push(...preservedLines);
  lines.push("");
}

writeFileSync(ENV_PATH, lines.join("\n") + "\n");
console.log(green("✓ .env created"));

// ---------------------------------------------------------------------------
// 2. Cloudflare resources
// ---------------------------------------------------------------------------

console.log(bold("\n── Cloudflare ──\n"));

const wranglerCheck = run("npx wrangler whoami", { silent: true });
if (!wranglerCheck) {
  console.log(yellow("⚠ Not authenticated — skipping resource provisioning"));
  console.log(dim("  Run: npx wrangler login"));
} else {
  const config = readWranglerConfig();
  let changed = false;

  // D1
  const d1Config = config.d1_databases?.[0];
  if (d1Config && isPlaceholder(d1Config.database_id)) {
    const dbName = d1Config.database_name;
    type D1Entry = { uuid: string; name: string };
    const list = runJson<D1Entry[]>("npx wrangler d1 list --json");
    const found = list?.find((db) => db.name === dbName);

    if (found) {
      updateWranglerField("database_id", found.uuid);
      console.log(green(`✓ D1 "${dbName}"`) + dim(` — found (${found.uuid.slice(0, 8)}...)`));
    } else {
      const output = run(`npx wrangler d1 create ${dbName}`, { silent: true });
      const match = output?.match(/database_id\s*=\s*"([^"]+)"/);
      if (match?.[1]) {
        updateWranglerField("database_id", match[1]);
        console.log(green(`✓ D1 "${dbName}"`) + dim(` — created (${match[1].slice(0, 8)}...)`));
      } else {
        console.log(yellow(`⚠ Failed to create D1 "${dbName}"`));
      }
    }
    changed = true;
  } else if (d1Config) {
    console.log(dim(`  D1 "${d1Config.database_name}" — already configured`));
  }

  // KV
  const kvConfig = config.kv_namespaces?.[0];
  if (kvConfig && isPlaceholder(kvConfig.id)) {
    const title = `${config.name}-${kvConfig.binding}`;
    type KvEntry = { id: string; title: string };
    const list = runJson<KvEntry[]>("npx wrangler kv namespace list --json");
    const found = list?.find((ns) => ns.title === title);

    if (found) {
      updateWranglerField("id", found.id);
      console.log(green(`✓ KV "${title}"`) + dim(` — found (${found.id.slice(0, 8)}...)`));
    } else {
      const output = run(`npx wrangler kv namespace create ${kvConfig.binding}`, { silent: true });
      const match = output?.match(/id\s*=\s*"([^"]+)"/);
      if (match?.[1]) {
        updateWranglerField("id", match[1]);
        console.log(green(`✓ KV "${title}"`) + dim(` — created (${match[1].slice(0, 8)}...)`));
      } else {
        console.log(yellow("⚠ Failed to create KV namespace"));
      }
    }
    changed = true;
  } else if (kvConfig) {
    console.log(dim(`  KV "${kvConfig.binding}" — already configured`));
  }

  // R2
  const r2Config = config.r2_buckets?.[0];
  if (r2Config) {
    const bucketName = r2Config.bucket_name;
    type R2Entry = { name: string };
    const list = runJson<R2Entry[]>("npx wrangler r2 bucket list --json");
    const found = list?.find((b) => b.name === bucketName);

    if (found) {
      console.log(dim(`  R2 "${bucketName}" — already exists`));
    } else {
      const result = run(`npx wrangler r2 bucket create ${bucketName}`, { silent: true });
      if (result) {
        console.log(green(`✓ R2 "${bucketName}"`) + dim(" — created"));
      } else {
        console.log(yellow(`⚠ Failed to create R2 "${bucketName}"`));
      }
    }
  }

  // Queue
  const queueConfig = config.queues?.producers?.[0];
  if (queueConfig) {
    const queueName = queueConfig.queue;
    type QueueEntry = { queue_name: string };
    const list = runJson<QueueEntry[]>("npx wrangler queues list --json");
    const found = list?.find((q) => q.queue_name === queueName);

    if (found) {
      console.log(dim(`  Queue "${queueName}" — already exists`));
    } else {
      const result = run(`npx wrangler queues create ${queueName}`, { silent: true });
      if (result) {
        console.log(green(`✓ Queue "${queueName}"`) + dim(" — created"));
      } else {
        console.log(yellow(`⚠ Failed to create queue "${queueName}"`));
      }
    }
  }

  if (changed) {
    console.log(dim(`\n  Updated ${WRANGLER_CONFIG}`));
  }

  console.log(dim("\n  For CI deploy, add this GitHub Actions secret:"));
  console.log(dim("    CLOUDFLARE_API_TOKEN — dash.cloudflare.com → API Tokens"));
}

// ---------------------------------------------------------------------------
// 3. Install deps
// ---------------------------------------------------------------------------

console.log(bold("\n── Dependencies ──\n"));
run("bun install");

// ---------------------------------------------------------------------------
// Done
// ---------------------------------------------------------------------------

console.log(bold("\n── Done ──\n"));
console.log(`  ${bold("bun dev")}     Start dev server`);
console.log(`  ${bold("bun ok")}      Type check + lint + tests`);
console.log("");
