name: Deploy Site

on:
  push:
    branches: [main]
    paths:
      - "meta/site/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to ingotjs.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.SITE_DEPLOY_TOKEN }}
          external_repository: ingotjs/ingotjs.github.io
          publish_branch: main
          publish_dir: ./meta/site
          cname: ingot.js.org
